[package]
name = "sim-expr-tree-calc"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false
description = "Scaffold for SIM expression-tree calculation."

[dependencies]
sim-expr-tree-core = { path = "../sim-expr-tree-core" }

[lints]
workspace = true
