[package]
name = "sim-expr-tree-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false
description = "Scaffold for SIM expression-tree core records."

[dependencies]
sim-table-core = { version = "0.1.2", path = "../../../sim-foundation/crates/sim-table-core" }

[lints]
workspace = true
