[package]
name = "sim-lib-expr-tree"
version = "0.1.0"
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
publish = true
description = "Loadable, Shape-checked SIM expression-tree runtime library."

[dependencies]
sim-citizen = { version = "0.1.2" }
sim-citizen-derive = { version = "0.1.3" }
sim-cookbook = { version = "0.1.4" }
sim-expr-tree-calc = { version = "0.1.0", path = "../sim-expr-tree-calc" }
sim-expr-tree-core = { version = "0.1.0", path = "../sim-expr-tree-core" }
sim-kernel = { version = "0.1.5" }
sim-lib-stream-core = { version = "0.1.3" }
sim-shape = { version = "0.1.3" }
sim-table-core = { version = "0.1.2" }

[build-dependencies]
sim-cookbook = { version = "0.1.4" }

[dev-dependencies]
sim-codec = { version = "0.1.6" }
sim-codec-lisp = { version = "0.1.2" }
sim-kernel = { version = "0.1.5", features = ["test-support"] }

[lints]
workspace = true
